
title: Suzuano
description: Personal blog about hacking & cybersecurity
baseurl: ""
url: "https://suzunao.github.io"
timezone: UTC

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never


permalink: /post/:title/


plugins:
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compose


pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  debug: false
  collection: 'posts'


jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: default
  permalinks:
    tag: '/tag/:name/'


search_enabled: true


# Optimizaciones de rendimiento
lazy_scroll: false

# Reducir tamaño del JSON de búsqueda
excerpt_max_length: 60


exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - .vscode
  - .idea
  - "*.psd"
  - "*.ai"
  - node_modules
